### ISSUE TITLE
CESM info

### ISSUE THREAD

**Issue by matt-long** [NCAR/cesm-hist2tseries#7]
Currently missing this file:
https://github.com/NCAR/cesm-hist2tseries/blob/deaf1234e4d68ff54f943f2d40fb16798e458b3e/cesm_hist2tseries.py#L160

**Comment by mgrover1** [comment]
It seems like using some of the functionality/ideas from the CESM_postprocessing repo would be helpful, for example, [this](https://github.com/NCAR/CESM_postprocessing/blob/master/Config/config_timeseries.xml) configuration file is similar to the `cesm_streams.yml`, with some additional information regarding the size of output netcdf files and flags for which variables to process to timeseries
